{% set name = "anaconda-assistant-conda" %}
{% set version = "0.5.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/anaconda_assistant_conda-{{ version }}.tar.gz
  sha256: 32ae6089608718982572612dab8819bb0ce9280cc26d45aa8845026603cab328

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - hatch-vcs >=0.3
    - setuptools-scm >=7.1
    - pip
  run:
    - python >={{ python_min }}
    - anaconda-cli-base >=0.5
    - anaconda-assistant-sdk >=0.4
    - anaconda-auth >=0.8
    - rich
    - requests
    - pydantic >=2
    - conda >=24.1
    - tomli
    - tomli-w

test:
  imports:
    - anaconda_assistant_conda
    - anaconda_assistant_conda.plugin
    - anaconda_assistant_conda.config
    - anaconda_assistant_conda.debug_config
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  summary: The Anaconda Assistant conda plugin
  doc_url: https://anaconda.github.io/assistant-sdk/conda
  dev_url: https://github.com/anaconda/assistant-sdk
  home: https://anaconda.com
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - AlbertDeFusco
